### ISSUE TITLE
Cannot remove Positive/Negative buttons after setting them

### ISSUE THREAD

**Issue by jishhd** [marcoscgdev/DialogSheet#10]
In my implementation, I'm reusing the same dialog sheet and modifying its title/body/button functionality based on specific conditions. However, if I add a positive or negative button in the DialogSheet's creator, I am unable to remove it from the view afterwards (for example, by using `setPositiveButton(null, null)`), like how I can change the Title of the Sheet after its creation & display.

It would be helpful to have a `removePositiveButton` `removeNegativeButton` etc methods, or for the `set` methods to support removing the button from the view by passing `null`s.

**Comment by marcoscgdev** [comment]
I will consider your suggestion for the upcoming release. Thank you for suggesting it! 😀

**Comment by marcoscgdev** [comment]
Added in [version 2.0.4](https://github.com/marcoscgdev/DialogSheet/releases/tag/2.0.4). You can now remove views dynamically by setting them to null:

`setNegativeButton(null, null);`
