### ISSUE TITLE
Dont dismiss in onClick() of positive button

### ISSUE THREAD

**Issue by JoseManuelMB** [marcoscgdev/DialogSheet#14]
I have a form in my dialogue sheet, but I validated it with a click on the positive button, but it closes.
It would be a good feature to choose whether to close or not

**Comment by owenlejeune** [comment]
I wanted this functionality too.  I have a PR up that would add this feature.

**Comment by marcoscgdev** [comment]
Functionality added in [release 2.0.6](https://github.com/marcoscgdev/DialogSheet/releases/tag/2.0.6) thanks to @owenlejeune.

**Comment by lucazin** [comment]
how can avoid dismiss on click?

**Comment by marcoscgdev** [comment]
> how can avoid dismiss on click?

You can set the shouldDismiss boolean to false when adding the button. 

```kotlin

setPositiveButton(android.R.string.ok, false) {
    Toast.makeText(this@MainActivity, "Positive button clicked!", Toast.LENGTH_SHORT).show()
}
```
