### ISSUE TITLE
I get xml error  exception.

### ISSUE THREAD

**Issue by queendevelopers** [marcoscgdev/DialogSheet#17]
`android.view.InflateException: Binary XML file line #6 in 
package:layout/layout_bottomdialog: Binary XML file line #32 in package:layout/layout_bottomdialog_content: Error inflating class android.support.v7.widget.AppCompatTextView
    Caused by: android.view.InflateException: Binary XML file line #32 in package:layout/layout_bottomdialog_content: Error inflating class android.support.v7.widget.AppCompatTextView`

**Comment by marcoscgdev** [comment]
Are you using appcompat library, androidx or have you modified the dialog layout?

**Comment by clintonblex2** [comment]
I'm using androidx and I'm having the same error above. Please, how can I resolve this error?

**Comment by marcoscgdev** [comment]
You have probably forgotten to add this mandatory attribute to the application style:

`<item name="dialogSheetAccent">@color/colorAccent</item>`

Check if adding the attribute solves the problem.

**Comment by clintonblex2** [comment]
Thanks, it worked
