### ISSUE TITLE
keyboard on dialogSheet

### ISSUE THREAD

**Issue by javiddeveloper** [marcoscgdev/DialogSheet#18]
When the dialog opened and the virtual keyboard is called, the dialog below the keyboard continues
This is scandal

**Comment by marcoscgdev** [comment]
This issue has already been fixed. It will be available in the next release.

**Comment by marcoscgdev** [comment]
Solved in [version 2.0.8](https://github.com/marcoscgdev/DialogSheet/releases/tag/2.0.8).
