### ISSUE TITLE
Feature Request : Change title, message and button font sizes

### ISSUE THREAD

**Issue by kariot** [marcoscgdev/DialogSheet#19]
Please provide a feature to change the font size of the contents in Dialog, Thank You

**Comment by marcoscgdev** [comment]
Added to [version 2.0.9](https://github.com/marcoscgdev/DialogSheet/releases/tag/2.0.9).

```java
setTitleTextSize(sizeInSp);
```

```java
setMessageTextSize(sizeInSp);
```

```java
setButtonsTextSize(sizeInSp);
```
