### ISSUE TITLE
setRoundedCorners not working on SDK 29

### ISSUE THREAD

**Issue by RasyiidWho** [marcoscgdev/DialogSheet#20]

**Comment by marcoscgdev** [comment]
After a lot of testing, I can confirm that setRoundedCorners is working on SDK 29.

**Comment by marcoscgdev** [comment]
After a lot of testing, the only bug that I have experienced with rounded corners is when you do not add the `dialogSheetAccent` attr to your app theme. This happens in all Android versions. It has been fixed in [version 2.0.9](https://github.com/marcoscgdev/DialogSheet/releases/tag/2.0.9).
