### ISSUE TITLE
Is this possible to add findFragmentById?

### ISSUE THREAD

**Issue by RasyiidWho** [marcoscgdev/DialogSheet#22]
Currently DialogSheet only support findViewById that's working really great. Is possible too to add findFragmentById in future update?

Thanks marcoscgdev for this great library :)

**Comment by RasyiidWho** [comment]
NVM, I have already done using MapView, but I got a new problem. The map always stucks whenever I try to move it around 2 secs..

**Comment by marcoscgdev** [comment]
That problem is occurring because the main dialog layout is a NestedScrollView, which gives problems to internal elements that need to be scrolled or touched.

You can solve this problem with the following code

Java:
```java
mapView.setOnTouchListener(new View.OnTouchListener() {
    public boolean onTouch(View v, MotionEvent event) {
        v.getParent().requestDisallowInterceptTouchEvent(true);
        return false;
    }
});
```

Kotlin:
```java
mapView.setOnTouchListener { v, _ ->
    v.parent.requestDisallowInterceptTouchEvent(true)
    false
}
```

**Comment by RasyiidWho** [comment]
> That problem is occurring because the main dialog layout is a NestedScrollView, which gives problems to internal elements that need to be scrolled or touched.
> 
> You can solve this problem with the following code
> 
> Java:
> 
> ```java
> mapView.setOnTouchListener(new View.OnTouchListener() {
>     public boolean onTouch(View v, MotionEvent event) {
>         v.getParent().requestDisallowInterceptTouchEvent(true);
>         return false;
>     }
> });
> ```
> 
> Kotlin:
> 
> ```java
> mapView.setOnTouchListener { v, _ ->
>     v.parent.requestDisallowInterceptTouchEvent(true)
>     false
> }
> ```

I have already tried, but sadly not working :(

I got an error
`E/InputDispatcher: Window handle Window{3d6e6f0 u0 id.net.routeteknis/id.net.routeteknis.teknis_laporan_tambah} has no registered input channel`

Here's the gif...

![gifnya](https://user-images.githubusercontent.com/19422415/73708145-28fea200-4730-11ea-9784-1b1421cfbcdc.gif)


My MapView codes..

```
        DialogLaporanMapView = dialogs.DialogLaporanMap.getInflatedView().getRootView();
        teknis_laporan_map = DialogLaporanMapView.findViewById(R.id.teknis_laporan_map);
        teknis_laporan_map.getMapAsync(ClientMapCallback());
        teknis_laporan_map.onCreate(Bundle.EMPTY);
        teknis_laporan_map.onResume();

        teknis_laporan_map.setOnTouchListener((v, event) -> {
            v.getParent().requestDisallowInterceptTouchEvent(true);
            Toast.makeText(v.getContext(), "TERDEMOK", Toast.LENGTH_SHORT).show();
            return false;
        });
```

Map callback..

```
    public OnMapReadyCallback ClientMapCallback() {
        return googleMap -> {
            this.laporan_googlemap = googleMap;
            laporan_googlemap.getUiSettings().setZoomControlsEnabled(true);
        };
    }
```

**Comment by marcoscgdev** [comment]
Can you please try to import this library version and remove the onTouchListener?

`implementation 'com.github.marcoscgdev:DialogSheet:672ca04fe6'`

Please tell me if it worked :)

**Comment by RasyiidWho** [comment]
> Can you please try to import this library version and remove the onTouchListener?
> 
> `implementation 'com.github.marcoscgdev:DialogSheet:672ca04fe6'`
> 
> Please tell me if it worked :)

In short answer, IT'S WORKING :D


It worked when I use it in `OnMapReadyCallback` with 2.0.9 version (figure out last night), but without `OnMapReadyCallback`, even I use latest version that you give (672ca04fe6) it's still not working :(

`OnMapReadyCallback` little buggy with `SetCancelable` set to true, sometime the DialogSheet just sliding down when I move the map..

`DialogLaporanMapView` is DialogSheet
`teknis_laporan_map` is MapView inside DialogSheet custom View

```
    public OnMapReadyCallback ClientMapCallback() {
        return googleMap -> {
            this.laporan_googlemap = googleMap;
            laporan_googlemap.getUiSettings().setZoomControlsEnabled(true);
            laporan_googlemap.setOnCameraMoveStartedListener(i -> {
                DialogLaporanMapView.getParent().requestDisallowInterceptTouchEvent(true);
                teknis_laporan_map.getParent().requestDisallowInterceptTouchEvent(true);
            });
        };
    }
```

I'm really glad to met developer like you,
Great Work Dev!

**Comment by marcoscgdev** [comment]
I'm glad to know that you have resolved your issue! :)
