### ISSUE TITLE
[Question] Different colors for buttons

### ISSUE THREAD

**Issue by kariot** [marcoscgdev/DialogSheet#24]
Is it possible to set different colors for buttons?

**Comment by marcoscgdev** [comment]
At this time only one color can be applied to all buttons. However, I leave this issue open in case I implement this functionality in the future. Thanks 😄

**Comment by marcoscgdev** [comment]
Feature added in [version 2.1.0](https://github.com/marcoscgdev/DialogSheet/releases/tag/2.1.0). Thanks for suggesting it! 😄
