### ISSUE TITLE
Icon size and icon in middle of dialog

### ISSUE THREAD

**Issue by lucazin** [marcoscgdev/DialogSheet#26]
How can set icon size ..? and put him in middle like readme?

**Comment by marcoscgdev** [comment]
To enable the new middle-icon dialog style, you have to pass a new parameter to the dialog constructor:

```java
val dialog = DialogSheet(context, true) // true if you want to use new dialog style, false otherwise.
```

At the moment it is not possible to change the size of the icon, but I will take it into account for future releases.
