### ISSUE TITLE
Interface OnPositiveClickListener does not have constructors

### ISSUE THREAD

**Issue by maxakash** [marcoscgdev/DialogSheet#28]
I am using the below code to set Positive Button 
```
 DialogSheet(context,true)
            .setColoredNavigationBar(true)
            .setTitle("Select language")
            .setTitleTextSize(20)
            .setTitleTypeface(type)
            .setView(dialogView)
            .setRoundedCorners(true)
            .setBackgroundColorRes(R.color.lightdark)
            .setPositiveButton("ok", true,DialogSheet.OnPositiveClickListener {
                deleteDownloadedFaces(context)
            })
            .show()
```

But I am getting the following error

```
Interface OnPositiveClickListener does not have constructors
```

Please suggest me a solution @marcoscgdev

**Comment by maxakash** [comment]
As I have added few buttons in my custom view, I want to dismiss the dialog sheet after clicking on them.
As I couldn't create a reference to the dialog sheet, how should I do it?
```
  val dialogSheet =  DialogSheet(context)
```
the type of dialogSheet is Unit, so it cannot be used to dismiss the dialogSheet.

@marcoscgdev

**Comment by marcoscgdev** [comment]
> I am using the below code to set Positive Button
> 
> ```
>  DialogSheet(context,true)
>             .setColoredNavigationBar(true)
>             .setTitle("Select language")
>             .setTitleTextSize(20)
>             .setTitleTypeface(type)
>             .setView(dialogView)
>             .setRoundedCorners(true)
>             .setBackgroundColorRes(R.color.lightdark)
>             .setPositiveButton("ok", true,DialogSheet.OnPositiveClickListener {
>                 deleteDownloadedFaces(context)
>             })
>             .show()
> ```
> 
> But I am getting the following error
> 
> ```
> Interface OnPositiveClickListener does not have constructors
> ```
> 
> Please suggest me a solution @marcoscgdev

Your code is working great for me. Are you using the latest library version?

You can also try with this snippet:

```java
DialogSheet(context,true)
    .setColoredNavigationBar(true)
    .setTitle("Select language")
    .setTitleTextSize(20)
    .setTitleTypeface(type)
    .setView(dialogView)
    .setRoundedCorners(true)
    .setBackgroundColorRes(R.color.lightdark)
    .setPositiveButton("ok", true) {
        deleteDownloadedFaces(context)
    })
    .show()
```

---

> As I have added few buttons in my custom view, I want to dismiss the dialog sheet after clicking on them.
> As I couldn't create a reference to the dialog sheet, how should I do it?
> 
> ```
>   val dialogSheet =  DialogSheet(context)
> ```
> 
> the type of dialogSheet is Unit, so it cannot be used to dismiss the dialogSheet.
> 
> @marcoscgdev

To avoid Unit type, you can create a reference like this:

```java
val dialogSheet: DialogSheet = DialogSheet(context)
```

Or, if you want to use the new dialog style (with centered icon):

```java
val dialogSheet: DialogSheet = DialogSheet(context, true)
```

And then, start your dialog configuration:

```java
dialogSheet.setColoredNavigationBar(true)
    .setTitle("Select language")
    .setTitleTextSize(20)
    ...
```
