### ISSUE TITLE
WindowManager BadTokenException when trying to show the dialog

### ISSUE THREAD

**Issue by AbreuY** [marcoscgdev/DialogSheet#29]
Hi, i'm getting this error on crashlitycs logs

Caused by android.view.WindowManager$BadTokenException
Unable to add window -- window android.view.ViewRootImpl$W@38d65ca has already been added

com.marcoscg.dialogsheet.DialogSheet.show (DialogSheet.java:453)

Maybe you can check if the activity is finishing before showing the dialog?

``` kotlin
fun Activity?.isAlive(): Boolean = this != null && !this.isFinishing 
```
library version: 2.1.2

Device
Brand: samsung
Model: Galaxy J7 Prime
Vertical orientation
Available RAM: 309.83 MB
Available disk space: 14.47 GB
OS Version: 7.0
Root Access: No

**Comment by marcoscgdev** [comment]
An activity is not the only type of context that can be used. If you are using an activity as a context, you should perform the check you have mentioned before showing the dialog:

```java
fun Activity?.isAlive(): Boolean = this != null && !this.isFinishing 
```

A priori, this error is not something that the library can manage.
