### ISSUE TITLE
Width - Landscape mode

### ISSUE THREAD

**Issue by lucazin** [marcoscgdev/DialogSheet#31]
Hi!

Can u help me ?
I need increase width from dialog in landscape mode..

how can i do that ?
thanks!

**Comment by lucazin** [comment]
i have a pdv and tablet..and i use in landscape mode.
I have a custom layout inside dialogsheet, but in landscape mode is not expand .. i need to expandthe size of container of dialog to  show better the layout. 

how can i increase width size ?  i download the lib and try everything.. but i cant.
can u help me ?

**Comment by lucazin** [comment]
can u help me?

**Comment by lucazin** [comment]
why this is fixed? 

  // Landscape fixed width
        val configuration = context.resources.configuration
        if (configuration.orientation == Configuration.ORIENTATION_LANDSCAPE &&
                configuration.screenWidthDp > 400) {
            if (bottomSheetDialog?.window != null) bottomSheetDialog?.window?.setLayout(dpToPx(400), -1)
        }

**Comment by marcoscgdev** [comment]
Hello @lucazin,

Sorry for the late reply, this library is a bit discontinued. I have just published a new version in which, in addition to updating Gradle and the Android SDK to the latest version, the width of the dialog in landscape mode has been parameterized.

You can change the size by overwriting the following dimen in your project:

```xml
<dimen name="dialog_sheet_landscape_width">400dp</dimen>
```

Thanks!
