### ISSUE TITLE
Ability to Listen to DialogSheet Dismissals

### ISSUE THREAD

**Issue by jishhd** [marcoscgdev/DialogSheet#9]
It would be quite helpful to have a listener that could be attached to a DialogSheet to have specific code run when the sheet is dismissed through `dismiss()`

**Comment by marcoscgdev** [comment]
There is actually a pre-release version that includes a dismiss listener:

```
implementation 'com.github.marcoscgdev:DialogSheet:2.0.4-pre1'
```

It is stable so you can use it without any problems.

**Comment by jishhd** [comment]
Thank you! Any timeline for a release version with that functionality?

**Comment by marcoscgdev** [comment]
If everything goes well, the new release version will be ready this weekend.

**Comment by marcoscgdev** [comment]
Added in [version 2.0.4](https://github.com/marcoscgdev/DialogSheet/releases/tag/2.0.4).
